Repository FEMessage/vant, pull requests merged in 2019-11, with the labels that each got.

#7 feat(select): 新增表单选择器组件
  docs/site/doc.config.js
  src/action-sheet/index.tsx
  src/field/index.js
  src/field/shared.ts
  src/index.less
  src/index.ts
  src/select/README.md
  src/select/README.zh-CN.md
  src/select/demo/index.vue
  src/select/index.js
  src/select/index.less
  src/select/test/__snapshots__/demo.spec.js.snap
  src/select/test/demo.spec.js
  types/index.d.ts
Labels: enhancement

#8 fix(select): overlay propagation
  src/overlay/index.tsx
  src/select/index.js
Labels: bug

#9 feat(select): options为 name/value 形式
  src/select/README.zh-CN.md
  src/select/demo/index.vue
  src/select/index.js
Labels: enhancement

#10 feat: address-list增加radio、edit、delete处的插槽
  src/address-list/Item.tsx
  src/address-list/README.md
  src/address-list/README.zh-CN.md
  src/address-list/index.tsx
Labels: enhancement

#12 feat: grid-item用icon插槽时也能用info属性
  package.json
  src/address-list/test/__snapshots__/demo.spec.js.snap
  src/address-list/test/__snapshots__/index.spec.js.snap
  src/grid-item/index.js
  src/grid/README.md
  src/grid/README.zh-CN.md
  src/grid/demo/index.vue
  src/grid/test/__snapshots__/demo.spec.js.snap
  src/grid/test/__snapshots__/index.spec.js.snap
  src/select/test/__snapshots__/demo.spec.js.snap
Labels: enhancement

#13 chore(deps): move some deps to devDeps
  package.json
Labels: dependencies
